version: '3.8'
services:

  # Backend Laravel (TAPAMAJUMA-API)
  app:
    build:
      context: ./tapamajuma-api
      dockerfile: Dockerfile
    image: tapamajuma-backend
    container_name: tapamajuma-api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      # Gunakan jalur lengkap agar tidak bingung dengan folder "Work" atau spasi
      - "/media/radotnababan/DATA1/Work/Tapamajuma PWA/Tapamajuma-PWA-/tapamajuma-api:/var/www"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - tapamajuma-network

  # Web Server (Nginx)
  nginx:
    image: nginx:alpine
    container_name: tapamajuma-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./tapamajuma-api:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - tapamajuma-network

networks:
  tapamajuma-network:
    driver: bridge