server {
    listen 80;
    index index.php index.html;
    root /var/www/frontend; # Ini nanti tempat file React berada

    # 1. Handle Request ke Frontend (React)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 2. Handle Request ke Backend (Laravel API)
    location ~ ^/api {
        alias /var/www/backend/public; # Mapping ke folder laravel
        try_files $uri $uri/ @laravel;
    }
    
    # Logic untuk PHP/Laravel
    location @laravel {
        rewrite /api/(.*)$ /api/$1 break;
        fastcgi_pass app:9000; # 'app' adalah nama service di docker-compose
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/backend/public/index.php;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}